In [ ]:
 import numpy as np
 

In [ ]:
arr=np.array([1,2,3])
arr

array([1, 2, 3])

In [ ]:
list_of_lists=[[1,2,3],[4,5,6],[7,8,9]]
np.array(list_of_lists)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

index slicing list square brcket is used other parenthesis can be used

In [ ]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(1,100)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [ ]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(1,46,5)

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41])

In [ ]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
np.zeros(10,int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
np.zeros(10,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
np.ones(100)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
np.ones(100,int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [ ]:
np.ones((2,5,),int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [ ]:
np.zeros((2,10),int)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [ ]:
np.linspace(0,20,8)

array([ 0.        ,  2.85714286,  5.71428571,  8.57142857, 11.42857143,
       14.28571429, 17.14285714, 20.        ])

In [ ]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
np.linspace(0,1,8)

array([0.        , 0.14285714, 0.28571429, 0.42857143, 0.57142857,
       0.71428571, 0.85714286, 1.        ])

In [ ]:
np.random.rand(3,2)

array([[0.48473256, 0.33731021],
       [0.95131606, 0.42096372],
       [0.97325016, 0.28171529]])

In [ ]:
np.random.randn(3,2)

array([[ 1.96528714,  0.30458354],
       [-1.14575931,  1.85506722],
       [-0.57969242,  0.52022263]])

In [ ]:
np.random.randint(3,10)

3

In [ ]:
np.random.randint(20,56,100)

array([48, 49, 20, 41, 40, 22, 45, 39, 29, 41, 46, 28, 28, 40, 36, 36, 29,
       45, 52, 54, 27, 53, 46, 51, 42, 37, 31, 29, 24, 38, 41, 39, 32, 50,
       22, 35, 40, 42, 55, 26, 33, 35, 50, 25, 22, 50, 24, 35, 29, 53, 35,
       34, 38, 25, 32, 32, 50, 47, 37, 37, 31, 31, 53, 50, 26, 27, 44, 33,
       35, 41, 55, 32, 49, 32, 48, 29, 38, 45, 54, 37, 52, 42, 22, 21, 38,
       51, 46, 36, 36, 48, 27, 40, 35, 31, 21, 40, 32, 54, 31, 52])

In [ ]:
rand_array=np.random.randint(0,100,20)
rand_array

array([76, 25, 95, 20, 78, 76, 40, 11, 64, 19, 98,  2, 37, 65, 12, 90, 70,
        7,  1, 71])

In [ ]:
sample_array=np.arange(30)
sample_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [ ]:
sample_array.reshape(5,6
                     )

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [ ]:
rand_array.min()

1

In [ ]:
rand_array.argmin()

18

In [ ]:
rand_array.max()

98

In [ ]:
rand_array.argmax()

10

In [ ]:
sample_array.dtype

dtype('int64')

In [ ]:
a=np.eye(5)
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
a.T


array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
a=np.random.rand(2,3)
a

array([[0.76502738, 0.90015166, 0.88929003],
       [0.80529005, 0.4614021 , 0.50072713]])

In [ ]:
sample_array=np.arange(10,21)
sample_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [ ]:
sample_array[-3]

18

In [ ]:
sample_array[3:7]

array([13, 14, 15, 16])

In [ ]:
sample_array[1:4]=100
sample_array

array([ 10, 100, 100, 100,  14,  15,  16,  17,  18,  19,  20])

In [ ]:
 sample_array=np.arange(10,21)
 sample_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [ ]:
subset_sample_array = sample_array[0:7]
subset_sample_array


array([10, 11, 12, 13, 14, 15, 16])

In [ ]:
subset_sample_array[1:4]=1001
subset_sample_array

array([  10, 1001, 1001, 1001,   14,   15,   16])

In [ ]:
two d array

In [ ]:
subset_sample_array[:]=1001
subset_sample_array

array([1001, 1001, 1001, 1001, 1001, 1001, 1001])

In [ ]:
sample_matrix=np.array(([50,20,1,23],[24,23,21,33],[56,76,24,7]))
sample_matrix

array([[50, 20,  1, 23],
       [24, 23, 21, 33],
       [56, 76, 24,  7]])

In [ ]:
sample_matrix[1][2]

21

In [ ]:
sample_matrix[2]

array([56, 76, 24,  7])

In [ ]:
sample_matrix[2,:]

array([56, 76, 24,  7])

 ' : ' = all numbers in the matrix

In [ ]:
sample_matrix[:,(3,2)]

array([[23,  1],
       [33, 21],
       [ 7, 24]])